### test request for actors index
GET http://localhost:3000/actors.json

### test request for actor show
GET http://localhost:3000/actors/1.json

### test request for actor create
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Andy",
  "last_name": "Rodginous",
  "favorite_animal": "Octopus",
  "known_for": "something good",
  "gender": "nimby",
  "age": "26"
}

### test request for actor update
PATCH http://localhost:3000/actors/24.json
Content-Type: application/json

{
  "gender": "non-binary",
  "age": 46
}

### test request for actor delete
DELETE http://localhost:3000/actors/1.json




### test request for movies index
GET http://localhost:3000/movies.json

### test request for movie show
GET http://localhost:3000/movies/1.json

### test request for movie create
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "",
  "year": "222",
  "plot": "Something about something",
  "director": "",
  "english": "true"
}

### test request for movie update
PATCH http://localhost:3000/movies/4.json
Content-Type: application/json

{
  "director": "Another Guy",
  "english": "false"
}

### test request for movie delete
DELETE http://localhost:3000/movies/1.json


### Test request for MovieGenre create
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id": 1,
  "genre_id": 1
}